# Generated by Django 6.1 on 2026-09-28 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('solicitud', models.TextField(verbose_name='Solicitud / Problema')),
                ('accion', models.CharField(max_length=300, verbose_name='Acción Realizada')),
                ('responsable', models.CharField(max_length=200)),
                ('item_evaluacion', models.CharField(max_length=200, verbose_name='Ítem de Evaluación')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Realizado', 'Realizado')], default='Pendiente', max_length=30)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('ingreso_tubo', models.BooleanField(default=False, verbose_name='Ingreso a Tubo')),
                ('codigo_evidencia', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de Evidencia')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('imagen_verificada', models.BooleanField(default=False)),
                ('verificador_valido', models.IntegerField(default=0)),
                ('resultado', models.IntegerField(default=0)),
                ('estado_validacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Corregir', 'Requiere Corrección')], default='Pendiente', max_length=30)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='actividades.actividad')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
