# Generated by Django 6.1.1 on 2026-10-07 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('solicitud', models.TextField(verbose_name='Solicitud / Problema')),
                ('accion', models.CharField(max_length=300, verbose_name='Acción Realizada')),
                ('responsable', models.CharField(max_length=200)),
                ('item_evaluacion', models.CharField(max_length=200, verbose_name='Ítem de Evaluación')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Realizado', 'Realizado')], default='Pendiente', max_length=30)),
                ('contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('ingreso_tubo', models.BooleanField(default=False, verbose_name='Ingreso a Tubo')),
                ('codigo_evidencia', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Evidencia')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_funcionario', models.ForeignKey(db_column='id_funcionario', on_delete=django.db.models.deletion.RESTRICT, related_name='actividades', to='organizacion.funcionario')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id_evidencia', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('archivo_ruta', models.CharField(max_length=255, verbose_name='Ruta / Nombre Archivo')),
                ('imagen_verificada', models.BooleanField(default=False)),
                ('verificador_valido', models.BooleanField(default=False)),
                ('resultado', models.IntegerField(default=0)),
                ('estado_validacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Corregir', 'Requiere Corrección')], default='Pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('id_actividad', models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='actividades.actividad')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'db_table': 'evidencias',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
