# Generated by Django 6.1 on 2026-09-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField()),
                ('actividad', models.TextField(verbose_name='Actividad / Solicitud / Problema')),
                ('tipo', models.CharField(choices=[('INT', 'Interno'), ('EXT', 'Externo')], default='EXT', max_length=10)),
                ('solicitante', models.CharField(max_length=200)),
                ('territorio', models.CharField(blank=True, max_length=200)),
                ('responsable', models.CharField(max_length=200)),
                ('fecha_compromiso', models.DateField(blank=True, null=True, verbose_name='Fecha Comprometida')),
                ('area_apoyo', models.CharField(blank=True, max_length=200, verbose_name='Área / Persona Apoyo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Avance / Observaciones')),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado'), ('PENDIENTE', 'Pendiente'), ('EN PROCESO', 'En Proceso'), ('REALIZADO', 'Realizado')], default='INGRESADO', max_length=20)),
                ('unidad', models.IntegerField(default=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compromiso',
                'verbose_name_plural': 'Compromisos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
