# Generated by Django 6.1.1 on 2026-10-07 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id_compromiso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('actividad', models.TextField(verbose_name='Actividad / Solicitud / Problema')),
                ('tipo', models.CharField(choices=[('INT', 'Interno'), ('EXT', 'Externo')], default='EXT', max_length=10)),
                ('solicitante', models.CharField(max_length=200)),
                ('territorio', models.CharField(blank=True, max_length=200, null=True)),
                ('responsable', models.CharField(max_length=200)),
                ('fecha_compromiso', models.DateField(blank=True, null=True, verbose_name='Fecha Comprometida')),
                ('area_apoyo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Área / Persona Apoyo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Avance / Observaciones')),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado'), ('PENDIENTE', 'Pendiente'), ('EN PROCESO', 'En Proceso'), ('REALIZADO', 'Realizado')], default='INGRESADO', max_length=20)),
                ('unidad', models.IntegerField(default=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_delegacion', models.ForeignKey(db_column='id_delegacion', on_delete=django.db.models.deletion.RESTRICT, related_name='compromisos', to='organizacion.delegacion')),
                ('id_responsable', models.ForeignKey(blank=True, db_column='id_responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromisos', to='organizacion.funcionario')),
            ],
            options={
                'verbose_name': 'Compromiso',
                'verbose_name_plural': 'Compromisos',
                'db_table': 'compromisos_tubo',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
