# Generated by Django 6.1.1 on 2026-10-07 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoEvaluacion',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('dias_totales', models.IntegerField(default=90)),
                ('dias_transcurridos', models.IntegerField(default=89)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Período de Evaluación',
                'verbose_name_plural': 'Períodos de Evaluación',
                'db_table': 'periodos_evaluacion',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MetaFuncionario',
            fields=[
                ('id_meta', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=200, verbose_name='Ítem de Evaluación')),
                ('ponderador', models.DecimalField(decimal_places=2, help_text='Porcentaje de ponderación (ej: 25.00 para 25%)', max_digits=5)),
                ('meta_periodo', models.IntegerField(verbose_name='Meta del Período')),
                ('avance_actual', models.IntegerField(default=0, verbose_name='Avance Actual')),
                ('porcentaje_cumplimiento', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cumplimiento_ponderado', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('felicitaciones', models.IntegerField(default=0)),
                ('reclamos', models.IntegerField(default=0)),
                ('id_funcionario', models.ForeignKey(db_column='id_funcionario', on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='organizacion.funcionario')),
                ('id_periodo', models.ForeignKey(blank=True, db_column='id_periodo', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='metas', to='resultados.periodoevaluacion')),
            ],
            options={
                'verbose_name': 'Meta de Funcionario',
                'verbose_name_plural': 'Metas de Funcionarios',
                'db_table': 'metas_funcionario',
                'ordering': ['id_funcionario', 'item'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorDelegacion',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=150)),
                ('responsable', models.CharField(max_length=200)),
                ('avance_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado_semaforo', models.CharField(choices=[('verde', 'Verde (Óptimo ≥ 98.9%)'), ('amarillo', 'Amarillo (Alerta ≥ 60%)'), ('rojo', 'Rojo (Crítico < 60%)')], default='verde', max_length=10)),
                ('licencias', models.IntegerField(default=0)),
                ('vacaciones', models.IntegerField(default=0)),
                ('emergencias', models.IntegerField(default=0)),
                ('compensatorios', models.IntegerField(default=0)),
                ('id_delegacion', models.ForeignKey(db_column='id_delegacion', on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='organizacion.delegacion')),
                ('id_periodo', models.ForeignKey(blank=True, db_column='id_periodo', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='indicadores', to='resultados.periodoevaluacion')),
            ],
            options={
                'verbose_name': 'Indicador de Delegación',
                'verbose_name_plural': 'Indicadores de Delegaciones',
                'db_table': 'indicadores_delegacion',
            },
        ),
    ]
