# Generated by Django 6.1 on 2026-09-28 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('dias_totales', models.IntegerField(default=90)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Período de Evaluación',
                'verbose_name_plural': 'Períodos de Evaluación',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorDelegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=150)),
                ('responsable', models.CharField(max_length=200)),
                ('avance_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado_semaforo', models.CharField(choices=[('verde', 'Verde (Óptimo)'), ('ambar', 'Ámbar (Alerta)'), ('rojo', 'Rojo (Crítico)')], default='verde', max_length=10)),
                ('licencias', models.IntegerField(default=0)),
                ('vacaciones', models.IntegerField(default=0)),
                ('emergencias', models.IntegerField(default=0)),
                ('compensatorios', models.IntegerField(default=0)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='organizacion.delegacion')),
            ],
            options={
                'verbose_name': 'Indicador de Delegación',
                'verbose_name_plural': 'Indicadores de Delegaciones',
            },
        ),
        migrations.CreateModel(
            name='MetaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='Ítem de Evaluación')),
                ('ponderador', models.DecimalField(decimal_places=2, help_text='Porcentaje de ponderación (ej: 25.00 para 25%)', max_digits=5)),
                ('meta_periodo', models.IntegerField(verbose_name='Meta del Período')),
                ('avance_actual', models.IntegerField(default=0, verbose_name='Avance Actual')),
                ('felicitaciones', models.IntegerField(default=0)),
                ('reclamos', models.IntegerField(default=0)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='organizacion.funcionario')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='resultados.periodoevaluacion')),
            ],
            options={
                'verbose_name': 'Meta de Funcionario',
                'verbose_name_plural': 'Metas de Funcionarios',
                'ordering': ['funcionario', 'item'],
            },
        ),
    ]
